=== Infosys/Infosys-Document-Workbench/components/java/common/CommonUtilsJAR/src/test/resources/schemaAttributeExtractorApiResponseV2.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"response",
		"transactionId",
		"responseCde",
		"responseMsg",
		"responseTimeInSecs",
		"timestamp"
	],
	"properties": {
		"response": {
			"type": "object",
			"oneOf": [
				{
					"$ref": "#/definitions/colTypeDef"
				}
			]
		},
		"transactionId": {
			"type": "string"
		},
		"responseCde": {
			"type": "integer"
		},
		"responseMsg": {
			"type": "string"
		},
		"responseTimeInSecs": {
			"type": "number"
		},
		"timestamp": {
			"type": "string"
		}
	},
	"definitions": {
		"colTypeDef": {
			"type": "object",
			"patternProperties": {
				"^table[1-9]+\\d*$": {
					"oneOf": [
						{
							"$ref": "#/definitions/tableDef"
						}
					]
				},
				"^attributes$": {
					"type": "array",
					"items": {
						"oneOf": [
							{
								"$ref": "#/definitions/columnDef"
							},
							{
								"$ref": "#/definitions/columnDefDynamic"
							}
						]
					},
					"uniqueItems": true,
					"minItems": 1
				}
			},
			"additionalProperties": false,
			"minProperties": 1
		},
		"tableDef": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"default": ""
				},
				"columnOrder": {
					"type": "array",
					"default": [],
					"items": {
						"type": "string",
						"default": ""
					},
					"minItems": 1
				},
				"columnLabels": {
					"type": "array",
					"default": [],
					"items": {
						"type": "string",
						"default": ""
					}
				}
			},
			"patternProperties": {
				"^row[1-9]+\\d*$": {
					"oneOf": [
						{
							"$ref": "#/definitions/rowDef"
						}
					]
				}
			},
			"additionalProperties": false,
			"minProperties": 3,
			"required": [
				"name",
				"columnOrder"
			]
		},
		"rowDef": {
			"type": "object",
			"patternProperties": {
				".*": {
					"anyOf": [
						{
							"$ref": "#/definitions/columnDefObject"
						},
						{
							"$ref": "#/definitions/columnDefOther"
						}
					]
				}
			},
			"additionalProperties": false,
			"minProperties": 1
		},
		"columnDef": {
			"type": "object",
			"patternProperties": {
				".*": {
					"oneOf": [
						{
							"$ref": "#/definitions/columnDefArray"
						},
						{
							"anyOf": [
								{
									"$ref": "#/definitions/columnDefObject"
								},
								{
									"$ref": "#/definitions/columnDefOther"
								}
							]
						}
					]
				}
			},
			"properties": {
				"label": {
					"type": "string",
					"default": ""
				}
			},
			"required": [
				"label"
			],
			"additionalProperties": false,
			"minProperties": 2,
			"maxProperties": 2
		},
		"columnDefDynamic": {
			"type": "object",
			"patternProperties": {
				".*": {
					"oneOf": [
						{
							"$ref": "#/definitions/columnDefArray"
						},
						{
							"anyOf": [
								{
									"$ref": "#/definitions/columnDefObject"
								},
								{
									"$ref": "#/definitions/columnDefOther"
								}
							]
						}
					]
				}
			},
			"additionalProperties": false,
			"minProperties": 1,
			"maxProperties": 1
		},
		"columnDefArray": {
			"type": "array",
			"items": {
				"anyOf": [
					{
						"$ref": "#/definitions/columnDefObject"
					},
					{
						"$ref": "#/definitions/columnDefOther"
					}
				]
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"columnDefObject": {
			"type": "object",
			"properties": {
				"value": {
					"type": "string"
				},
				"confidencePct": {
					"type": "number"
				}
			},
			"patternProperties": {
				".*": {
					"type": [
						"number",
						"string",
						"boolean",
						"integer"
					]
				}
			},
			"additionalProperties": false,
			"minProperties": 1,
			"required": [
				"value"
			]
		},
		"columnDefOther": {
			"type": [
				"number",
				"string",
				"boolean",
				"integer"
			],
			"additionalProperties": false,
			"minProperties": 1
		}
	}
}

=== Infosys/Infosys-Document-Workbench/components/java/common/CommonUtilsJAR/src/test/resources/response.json
{
  "response": {
    "attributes": [
      {
        "quoteNumber": "Quote # 11803873"
      },
      {
        "signatureDetected": false
      }
    ],
    "table1": {
      "name": "Proposal",
      "columnOrder": [
        "Pricing Prepared For",
        "Prepared On",
        "Price Valid Until",
        "Currency",
        "Total Mrc",
        "Total Nrc"
      ],
      "columnLabels": [
        "Pricing Prepared For",
        "Prepared On",
        "Price Valid Until",
        "Currency",
        "Total Mrc",
        "Total Nrc"
      ],
      "row1": {
        "Pricing Prepared For": "Telstra USA",
        "Prepared On": "01/31/2020",
        "Price Valid Until": "04/29/2020",
        "Currency": "USD",
        "Total Mrc": "852.65",
        "Total Nrc": "0.00"
      }
    },
    "table2": {
      "name": "Product Information",
      "columnOrder": [
        "Term",
        "Total Mrc",
        "Total Nrc",
        "# Sites"
      ],
      "columnLabels": [
        "Term",
        "Total Mrc",
        "Total Nrc",
        "# Sites"
      ],
      "row1": {
        "Term": "1 Year",
        "Total Mrc": "852.65",
        "Total Nrc": ".00",
        "# Sites": "1"
      }
    },
    "table3": {
      "name": "Location",
      "columnOrder": [
        "Pricing Prepared For",
        "Prepared On",
        "Price Valid Until",
        "Currency",
        "Total Mrc",
        "Total Nrc"
      ],
      "columnLabels": [
        "Pricing Prepared For",
        "Prepared On",
        "Price Valid Until",
        "Currency",
        "Total Mrc",
        "Total Nrc"
      ],
      "row1": {
        "Site Name": "CPHLPAAP 3543 SIMPSON FERRY RD - L3 POP COMMON DMARC",
        "Countr y": "USA",
        "Site Address": "3543 SIMPSON FERRY RD CAMP HILL, PA 17011",
        "USF": "Interstate",
        "Mrc": "852.65",
        "Nrc": ".00",
        "Port": "Fast Ethernet (100 Mb)",
        "Mrc.1": "687.75",
        "Nrc.1": ".00",
        "Mrc.2": "164.90",
        "Nrc.2": ".00"
      }
    },
    "table4": {
      "name": "Product Detail",
      "columnOrder": [
        "Description",
        "Qty",
        "Mrc",
        "Nrc",
        "Priced Amount",
        "Mrc Per"
      ],
      "columnLabels": [
        "Description",
        "Qty",
        "Mrc",
        "Nrc",
        "Priced Amount",
        "Mrc Per"
      ],
      "row1": {
        "Description": "A - 3543 SIMPSON FERRY RD CAMP HILL, PA 17011  On Net Access - Fast Ethernet (100 Mb) - [Bandwidth = Fast Ethernet (100 Mb), Sub Bandwidth = 100]",
        "Qty": "1",
        "Mrc": "164.90",
        "Nrc": "0.00",
        "Priced Amount": "",
        "Mrc Per": ""
      },
      "row2": {
        "Description": "A - 3543 SIMPSON FERRY RD CAMP HILL, PA 17011 IP VPN Port - Fast Ethernet (100 Mb) - [Bandwidth = Fast Ethernet (100 Mb), Network Integrity = No, CRTP = No, Multicast = No]",
        "Qty": "1",
        "Mrc": "75.00",
        "Nrc": "0.00",
        "Priced Amount": "",
        "Mrc Per": ""
      },
      "row3": {
        "Description": "A - 3543 SIMPSON FERRY RD CAMP HILL, PA 17011 Commit - Basic Plus & Basic - [Capacity (Mb) = 50.000]",
        "Qty": "1",
        "Mrc": "612.75",
        "Nrc": "0.00",
        "Priced Amount": "50.000",
        "Mrc Per": "12.26/Mb"
      }
    }
  },
  "transactionId": "848119814",
  "responseCde": 0,
  "responseMsg": "Success",
  "responseTimeInSecs": 0,
  "timestamp": "2020-06-24 09:50:39 PM"
}
